### ISSUE TITLE
Use netlify's deploy preview to pull-request

### ISSUE THREAD

**Issue by rinsuki** [mastodon/documentation#741]
https://www.netlify.com/blog/2016/07/20/introducing-deploy-previews-in-netlify/

This allows reviewer to see what the site actually changes like without having to pull the changes locally.

**Comment by vmstan** [comment]
The project has been using Vercel to generate previews and intends to enable to GitHub pages previews once those are available. Unfortunately many options all limited in what contributors can generate them on the free plans. Closing as completed because of Vercel but know we want to make this even better.
